### ISSUE TITLE
Adding a `keyPrefix` so that all cache keys are namespaced?

### ISSUE THREAD

**Issue by chrisspiegl** [dabroek/node-cache-manager-redis-store#16]
May be an interesting idea to add a `keyPrefix` so that all cache elements stored with the store are - well - prefixed by it, making name-spacing easy.

**Comment by vasyl-ivanchuk** [comment]
@chrisspiegl Have you tried to use `prefix` parameter?

```
const redisCache = cacheManager.caching({
  store: redisStore,
  host: 'localhost', // default value
  port: 6379, // default value
  auth_pass: 'XXXXX',
  db: 0,
  ttl: 600,
  prefix: 'cache:'
});
```
these parameters are passed to `redis` and according to the documentation `prefix` [should work](https://github.com/NodeRedis/node-redis#options-object-properties). Please keep in mind that the `keys` function won't be prefixed.

**Comment by chrisspiegl** [comment]
Thanks for this thought. I will keep this in mind.
It's always a bit tricky for me to get through and understand all the layers of the different libraries at play there.
