### ISSUE TITLE
Precisions

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [dabroek/node-cache-manager-redis-store#2]
I have 2 questions.

- The example of Multi-store, the ttl are in seconds?
- If we need to store 3 different data (including 2 different delays), what is the best to do?
  - 3 stores, or prefix Id?
  - Impact to redis connection(s)

**Comment by dabroek** [comment]
> The example of Multi-store, the ttl are in seconds?
The ttl is indeed in seconds.
> If we need to store 3 different data (including 2 different delays), what is the best to do?
Why not just implement a different method per data type to store your keys? For example:
`const saveType1 = (key, value) => redisCache.set(key, value, { ttl: 5 })`
`const saveType2 = (key, value) => redisCache.set(key, value, { ttl: 10 })`
`const saveType3 = (key, value) => redisCache.set(key, value, { ttl: 15 })`
