### ISSUE TITLE
Typescript declaration

### ISSUE THREAD

**Issue by amirqasemi74** [dabroek/node-cache-manager-redis-store#20]
Any typescript declaration?

**Comment by Maelstromeous** [comment]
I would love to see this too, right now I can't use your package!

**Comment by dabroek** [comment]
I am happy to inform you that I have just released [v3.0.0](https://github.com/dabroek/node-cache-manager-redis-store/releases/tag/v3.0.0) of this package on [npm](https://www.npmjs.com/package/cache-manager-redis-store) which upgrades the redis dependency to redis@^4.3.1 and adds new TypeScript declarations.
