### ISSUE TITLE
scan support

### ISSUE THREAD

**Issue by stuk88** [dabroek/node-cache-manager-redis-store#3]
Hey.
Do this package supports scan function?

**Comment by dabroek** [comment]
Hey Stas, it does not because the original [node-cache-manager](https://github.com/BryanDonovan/node-cache-manager) does not support it (yet). If you add an additional SCAN method to this package, you can subsequently implement the use of it in this package.

**Comment by josh803316** [comment]
Hi @dabroek - How can we utilize scan via node-redis? I'm trying to implement a (key) pattern matching controller that will execute in Production but I would prefer to use scan than keys (which is not recommended). Any suggestions?
