### ISSUE TITLE
del and reset methods don't return Promise

### ISSUE THREAD

**Issue by hugoduraes** [dabroek/node-cache-manager-redis-store#5]
Any specific reason why `del` and `reset` methods don't return Promises?

**Comment by dabroek** [comment]
No idea. I've [added](809fec23242c3b7e4223de156d73e1664a7b8449) promise support for `del`, `reset`, and `ttl` in the newest release (v.1.3.0).

**Comment by hugoduraes** [comment]
Thank you!
